import { AgencyRequest, SectorUseCase, TrainingProgram } from './types'

export const trainingPrograms: TrainingProgram[] = [
    {
        id: 'threat-assessment',
        name: 'تحليل التهديدات الأمنية وبناء مؤشرات الإنذار',
        summary: 'برنامج تطبيقي يساعد الفرق الأمنية على قراءة المؤشرات المبكرة وتحويلها إلى قرارات تشغيلية.',
        targetAudience: 'ضباط التخطيط، مراكز العمليات، وحدات التحليل الأمني',
        problem: 'تشتت مصادر المعلومات وصعوبة تحويل المؤشرات إلى أولويات تنفيذية.',
        outcomes: [
            'بناء مصفوفة تهديد',
            'صياغة مؤشرات إنذار',
            'رفع جودة التقارير الأمنية',
            'ربط التحليل بإجراءات الاستجابة',
        ],
        modules: ['منهجيات تحليل التهديد', 'مصادر البيانات الأمنية', 'تصميم مؤشرات الإنذار', 'تمرين غرفة عمليات'],
        durationDays: 5,
        language: 'العربية',
        valueForAgency: 'توحيد لغة التحليل ورفع سرعة الاستجابة للمتغيرات الأمنية.',
        relatedProgramIds: ['crisis-command', 'risk-governance'],
        sectorIds: ['security-agencies', 'security-leadership', 'risk-safety'],
        basePrice: 42000,
    },
    {
        id: 'border-risk',
        name: 'إدارة مخاطر المنافذ والحدود',
        summary: 'مسار عملي لتحسين الفرز، إدارة المخاطر، وتنسيق العمل بين الجهات العاملة في المنافذ.',
        targetAudience: 'مشرفو المنافذ، ضباط الجمارك، وحدات التفتيش، فرق التنسيق الحدودي',
        problem: 'تباين إجراءات التقييم وصعوبة المواءمة بين السرعة التشغيلية والضبط الأمني.',
        outcomes: ['نموذج فرز مخاطر', 'تحسين إجراءات التفتيش', 'تحديد نقاط الضعف', 'رفع التنسيق بين الفرق'],
        modules: ['خرائط المخاطر الحدودية', 'تقنيات الفرز', 'إدارة الحالات الاشتباهية', 'مؤشرات الأداء'],
        durationDays: 4,
        language: 'العربية',
        valueForAgency: 'تحسين كفاءة المنفذ وتقليل المخاطر دون تعطيل الحركة التشغيلية.',
        relatedProgramIds: ['threat-assessment', 'risk-governance'],
        sectorIds: ['ports-borders', 'risk-safety'],
        basePrice: 36000,
    },
    {
        id: 'aviation-security',
        name: 'الأمن الوقائي في بيئات الطيران الأمني',
        summary: 'برنامج يربط إجراءات السلامة، تقييم المخاطر، وإدارة الحوادث في عمليات الطيران الأمني.',
        targetAudience: 'قيادات الطيران الأمني، مسؤولو السلامة، ضباط العمليات الجوية',
        problem: 'الحاجة إلى مواءمة القرار الأمني مع متطلبات السلامة وسرعة الاستجابة.',
        outcomes: ['تحسين تقييم المخاطر الجوية', 'إعداد خطة استجابة', 'تعزيز الانضباط التشغيلي', 'رفع جاهزية الفرق'],
        modules: ['مخاطر بيئات الطيران', 'إدارة بلاغات الحوادث', 'التنسيق الميداني', 'محاكاة قرار تشغيلي'],
        durationDays: 5,
        language: 'العربية والإنجليزية',
        valueForAgency: 'رفع الجاهزية وتقليل المخاطر التشغيلية في المهمات الحساسة.',
        relatedProgramIds: ['crisis-command', 'risk-governance'],
        sectorIds: ['security-aviation', 'risk-safety'],
        basePrice: 52000,
    },
    {
        id: 'digital-forensics',
        name: 'التحقيق الرقمي وإدارة الأدلة الجنائية',
        summary: 'برنامج يركز على حفظ الدليل الرقمي، سلاسل الحيازة، وصياغة التقارير الفنية القابلة للاعتماد.',
        targetAudience: 'المحققون، خبراء الأدلة الجنائية، وحدات الجرائم المعلوماتية',
        problem: 'تحديات جمع الأدلة الرقمية وتوثيقها بصورة منهجية قابلة للمراجعة.',
        outcomes: ['إدارة سلسلة الحيازة', 'تحليل أولي للأدلة', 'صياغة تقرير فني', 'تقليل أخطاء التوثيق'],
        modules: ['مبادئ الدليل الرقمي', 'إجراءات التحريز', 'تحليل الأجهزة', 'كتابة التقرير'],
        durationDays: 6,
        language: 'العربية',
        valueForAgency: 'رفع جودة التحقيقات الرقمية وتعزيز موثوقية المخرجات الفنية.',
        relatedProgramIds: ['cyber-incident', 'threat-assessment'],
        sectorIds: ['forensics', 'cybersecurity'],
        basePrice: 58000,
    },
    {
        id: 'cyber-incident',
        name: 'الاستجابة للحوادث السيبرانية للجهات الأمنية',
        summary: 'برنامج لتطوير آلية استقبال البلاغات، احتواء الحوادث، والتنسيق مع أصحاب المصلحة.',
        targetAudience: 'فرق الأمن السيبراني، مراكز العمليات، مدراء التقنية',
        problem: 'بطء الاستجابة للحوادث بسبب عدم وضوح الأدوار ومسارات التصعيد.',
        outcomes: ['خطة استجابة', 'مصفوفة أدوار', 'تمارين احتواء', 'تقرير ما بعد الحادث'],
        modules: ['تصنيف الحوادث', 'إجراءات الاحتواء', 'التواصل أثناء الأزمة', 'تمرين طاولة'],
        durationDays: 5,
        language: 'العربية والإنجليزية',
        valueForAgency: 'تقليل أثر الحوادث ورفع نضج الاستجابة المؤسسية.',
        relatedProgramIds: ['digital-forensics', 'crisis-command'],
        sectorIds: ['cybersecurity', 'security-agencies'],
        basePrice: 56000,
    },
    {
        id: 'strategic-leadership',
        name: 'القيادة الأمنية الاستراتيجية',
        summary: 'برنامج للقيادات يركز على القرار، الحوكمة، إدارة الأولويات، وبناء فرق عالية الجاهزية.',
        targetAudience: 'القيادات الأمنية، مدراء الإدارات، قادة البرامج والمبادرات',
        problem: 'الحاجة إلى تحويل الرؤية الأمنية إلى مبادرات قابلة للتنفيذ والقياس.',
        outcomes: ['خارطة أولويات', 'نموذج حوكمة', 'تحسين القرار القيادي', 'مؤشرات أثر تدريبي'],
        modules: ['قراءة البيئة الأمنية', 'إدارة الأولويات', 'حوكمة المبادرات', 'قياس الأثر'],
        durationDays: 4,
        language: 'العربية',
        valueForAgency: 'تعزيز قدرة القيادات على توجيه الموارد وبناء أثر مؤسسي واضح.',
        relatedProgramIds: ['crisis-command', 'risk-governance'],
        sectorIds: ['security-leadership', 'security-agencies'],
        basePrice: 48000,
    },
    {
        id: 'crisis-command',
        name: 'إدارة الأزمات ومراكز القيادة والسيطرة',
        summary: 'برنامج تطبيقي لمحاكاة القرار أثناء الأزمات وتنسيق غرف العمليات متعددة الجهات.',
        targetAudience: 'مراكز العمليات، قادة الاستجابة، فرق الطوارئ والتنسيق',
        problem: 'تداخل الأدوار وضعف تدفق المعلومات أثناء الأزمات المركبة.',
        outcomes: ['نموذج قيادة وسيطرة', 'خطة اتصال', 'سيناريو تمرين', 'تحسين التصعيد'],
        modules: ['دورة الأزمة', 'تصميم غرفة عمليات', 'إدارة الاتصال', 'محاكاة أزمة'],
        durationDays: 5,
        language: 'العربية',
        valueForAgency: 'رفع الجاهزية وتحسين التنسيق وقت الضغط العالي.',
        relatedProgramIds: ['threat-assessment', 'strategic-leadership'],
        sectorIds: ['security-agencies', 'security-leadership', 'risk-safety'],
        basePrice: 50000,
    },
    {
        id: 'risk-governance',
        name: 'حوكمة السلامة وإدارة المخاطر الأمنية',
        summary: 'برنامج يبني إطارًا عمليًا لإدارة المخاطر، متابعة الضوابط، وقياس الالتزام.',
        targetAudience: 'وحدات السلامة، إدارة المخاطر، مدراء الالتزام، مشرفو العمليات',
        problem: 'غياب نموذج موحد لتسجيل المخاطر وربطها بالضوابط ومؤشرات الأداء.',
        outcomes: ['سجل مخاطر', 'مصفوفة ضوابط', 'مؤشرات متابعة', 'تقرير تنفيذي'],
        modules: ['مبادئ الحوكمة', 'تقييم المخاطر', 'تصميم الضوابط', 'المتابعة والتقارير'],
        durationDays: 4,
        language: 'العربية',
        valueForAgency: 'تحويل المخاطر إلى خطة متابعة واضحة وقابلة للقياس.',
        relatedProgramIds: ['threat-assessment', 'border-risk'],
        sectorIds: ['risk-safety', 'ports-borders', 'security-leadership'],
        basePrice: 39000,
    },
]

export const sectorUseCases: SectorUseCase[] = [
    {
        id: 'security-agencies',
        name: 'الجهات الأمنية',
        description: 'احتياجات مؤسسية مرتبطة بالتحليل، العمليات، الاستجابة، وتطوير القدرات الأمنية.',
        needs: ['رفع جودة التحليل', 'توحيد إجراءات الاستجابة', 'بناء مسارات تخصصية', 'قياس أثر التدريب'],
        suitableProgramIds: ['threat-assessment', 'cyber-incident', 'crisis-command', 'strategic-leadership'],
        suggestedTracks: ['مسار جاهزية العمليات الأمنية', 'مسار التحليل والاستجابة', 'مسار القيادات التنفيذية'],
        trainingValue: 'تحسين القدرة المؤسسية على تحويل الاحتياج إلى برامج قابلة للتنفيذ والقياس.',
    },
    {
        id: 'ports-borders',
        name: 'المنافذ والحدود',
        description: 'بيئات تشغيلية تحتاج إلى سرعة قرار، فرز مخاطر، وتنسيق ميداني دقيق.',
        needs: ['تحسين الفرز', 'إدارة الحالات الاشتباهية', 'تقليل التباين الإجرائي', 'رفع التنسيق'],
        suitableProgramIds: ['border-risk', 'threat-assessment', 'risk-governance'],
        suggestedTracks: ['مسار كفاءة المنفذ الآمن', 'مسار إدارة مخاطر التفتيش'],
        trainingValue: 'رفع كفاءة القرار الميداني وتقليل مخاطر العبور غير النظامي.',
    },
    {
        id: 'security-aviation',
        name: 'الطيران الأمني',
        description: 'عمليات حساسة تتطلب توافقًا بين السلامة، الأمن، وإدارة الحوادث.',
        needs: ['جاهزية فرق العمليات', 'تقييم مخاطر المهمات', 'تحسين الاستجابة للحوادث', 'تعزيز الانضباط'],
        suitableProgramIds: ['aviation-security', 'crisis-command', 'risk-governance'],
        suggestedTracks: ['مسار السلامة والجاهزية الجوية', 'مسار قيادة حادث طيران أمني'],
        trainingValue: 'تقليل المخاطر التشغيلية وتحسين جودة الاستجابة في المهمات الأمنية.',
    },
    {
        id: 'forensics',
        name: 'التحقيق والأدلة الجنائية',
        description: 'مجال تخصصي يحتاج إلى دقة إجرائية وتوثيق متين للأدلة والتقارير.',
        needs: ['حفظ الأدلة', 'رفع جودة التقارير', 'توحيد إجراءات التحريز', 'تحسين التكامل مع التحقيق'],
        suitableProgramIds: ['digital-forensics', 'cyber-incident', 'threat-assessment'],
        suggestedTracks: ['مسار المحقق الرقمي', 'مسار جودة الدليل والتقرير'],
        trainingValue: 'تعزيز موثوقية الدليل ورفع كفاءة التحقيقات الفنية.',
    },
    {
        id: 'cybersecurity',
        name: 'الأمن السيبراني',
        description: 'احتياج متنامٍ للاستجابة السريعة، التحقيق الرقمي، وحوكمة الحوادث.',
        needs: ['تقليل زمن الاستجابة', 'تحسين التصعيد', 'توثيق الحوادث', 'بناء تمارين محاكاة'],
        suitableProgramIds: ['cyber-incident', 'digital-forensics', 'crisis-command'],
        suggestedTracks: ['مسار الاستجابة والتحقيق السيبراني', 'مسار جاهزية مركز العمليات'],
        trainingValue: 'رفع نضج الاستجابة للحوادث وتقليل الأثر التشغيلي والسمعي.',
    },
    {
        id: 'security-leadership',
        name: 'القيادات الأمنية',
        description: 'مسارات قيادية تساعد على ربط الأولويات الأمنية بالحوكمة والنتائج.',
        needs: ['تطوير القرار القيادي', 'حوكمة المبادرات', 'بناء مؤشرات أثر', 'إدارة الأزمات'],
        suitableProgramIds: ['strategic-leadership', 'crisis-command', 'risk-governance'],
        suggestedTracks: ['مسار القيادة الأمنية التنفيذية', 'مسار حوكمة الجاهزية'],
        trainingValue: 'تحويل الرؤية الأمنية إلى مبادرات تدريبية ذات أثر واضح.',
    },
    {
        id: 'risk-safety',
        name: 'السلامة وإدارة المخاطر',
        description: 'احتياج مشترك بين القطاعات لبناء سجل مخاطر وضوابط متابعة فعالة.',
        needs: ['تقييم المخاطر', 'متابعة الضوابط', 'بناء مؤشرات', 'إعداد تقارير تنفيذية'],
        suitableProgramIds: ['risk-governance', 'threat-assessment', 'aviation-security', 'border-risk'],
        suggestedTracks: ['مسار الحوكمة والضوابط', 'مسار السلامة التشغيلية'],
        trainingValue: 'بناء لغة موحدة للمخاطر وربط التدريب بتحسينات قابلة للقياس.',
    },
]

export const agencyRequests: AgencyRequest[] = [
    {
        id: 'REQ-2401',
        agencyName: 'إدارة أمنية وطنية',
        sectorId: 'security-agencies',
        requestDate: '2026-06-03',
        status: 'جاهز للمراجعة',
        analysis: 'احتياج مركب في تحليل التهديدات وإدارة الأزمات.',
        suggestedPrograms: ['threat-assessment', 'crisis-command'],
        track: 'مسار جاهزية العمليات الأمنية',
        cost: 148000,
        proposal: 'عرض مختصر جاهز للمراجعة',
        nextAction: 'مراجعة المخرجات وتثبيت جدول التنفيذ',
    },
    {
        id: 'REQ-2402',
        agencyName: 'هيئة منافذ حدودية',
        sectorId: 'ports-borders',
        requestDate: '2026-06-07',
        status: 'قيد التحليل',
        analysis: 'الحاجة إلى تحسين الفرز وتوحيد إجراءات الاشتباه.',
        suggestedPrograms: ['border-risk', 'risk-governance'],
        track: 'مسار كفاءة المنفذ الآمن',
        cost: 112000,
        proposal: 'بانتظار اعتماد البرامج',
        nextAction: 'استكمال بيانات المشاركين والموقع',
    },
    {
        id: 'REQ-2403',
        agencyName: 'مركز عمليات سيبرانية',
        sectorId: 'cybersecurity',
        requestDate: '2026-06-10',
        status: 'جاهز للإرسال',
        analysis: 'فجوة في التصعيد والتوثيق أثناء الحوادث.',
        suggestedPrograms: ['cyber-incident', 'digital-forensics'],
        track: 'مسار الاستجابة والتحقيق السيبراني',
        cost: 164000,
        proposal: 'خطاب وعرض جاهزان',
        nextAction: 'إرسال العرض الرسمي للجهة',
    },
]

export const contentCenter = [
    {
        title: 'قالب خطاب ترشيح برنامج',
        type: 'قوالب خطابات',
        summary: 'صيغة رسمية موجزة لعرض برنامج تدريبي واحد على جهة مستفيدة.',
    },
    {
        title: 'قالب عرض مسار تدريبي',
        type: 'قوالب عروض',
        summary: 'هيكل عرض تنفيذي لمسار يضم عدة برامج مع المخرجات والتكلفة.',
    },
    {
        title: 'دليل ترشيح البرامج حسب القطاع',
        type: 'أدلة ترشيح',
        summary: 'مصفوفة تساعد فريق تطوير الأعمال على ربط الاحتياج بالبرنامج المناسب.',
    },
    {
        title: 'أسئلة شائعة للجهات المستفيدة',
        type: 'أسئلة شائعة',
        summary: 'إجابات قصيرة حول الطلب، التنفيذ، اللغة، المكان، والتقارير.',
    },
    {
        title: 'آلية طلب برنامج تدريبي',
        type: 'إرشادات',
        summary: 'خطوات الطلب من إدخال الاحتياج حتى استلام العرض الرسمي.',
    },
    {
        title: 'آلية بناء مسار تدريبي',
        type: 'إرشادات',
        summary: 'طريقة جمع البرامج في مسار مترابط حسب الفئة والمخرجات.',
    },
    {
        title: 'نموذج أثر تدريبي مختصر',
        type: 'نماذج أثر',
        summary: 'نموذج أولي لقياس رضا المشاركين والتحسن المتوقع بعد التنفيذ.',
    },
]
